name: Skript-Frame
author: Anarchick
description: A skript addon for image on item frames
version: 1.0-alpha1
main: fr.anarchick.skriptframe.SkriptFrame
depend: [Skript]
softdepend: [BKCommonLib]
website: www.github.com/Anarchick/skript-frame