name: Skript-Frame
author: Anarchick
description: A skript addon for image on item frame
version: 1.0
main: fr.anarchick.skriptframe.SkriptFrame
depend: [Skript]
softdepend: [BKCommonLib]
website: www.github.com/Anarchick/skript-frame